ccfd/src/analyze.h File Reference
Contains the structure definitions of wing_t and recordPoint_t
#include <stdlib.h>
#include <stdbool.h>
#include `main.h`
#include `boundary.h`
#include `mesh.h`
Data Structures
struct wing_t
Collection of all necessary values for the calculation of CL and CD.
struct recordPoint_t
Recording point structure, used to output flow field at specific points.
Functions
void initAnalyze (void)
Initialize the analysis function.
void analyze (double time, long iter, double resIter[NVAR+2])
Compute aerodynamic coefficients and extract values at record points.
void calcErrors (double time)
Calculate L1, L2, and Linf error norms, between the flow solution and the exact solution.
void globalResidual (double resIter[NVAR+2])
Calculate the global residual of the conservative variables.
void freeAnalyze (void)
Free all memory that was allocated for the wing evaluation.
Variables
bool doCalcWing
wing_t wing
recordPoint_t recordPoint
bool hasExactSolution
Detailed Description
Contains the structure definitions of wing_t and recordPoint_t
Author
hhh
Date
Sun 29 Mar 2020 05:51:23 PM CEST
Function Documentation
analyze()
void analyze (double time, long iter, double resIter[NVAR+2])
Compute aerodynamic coefficients and extract values at record points.
Parameters
 in time Calculation time at output
 in iter Iteration count at output
 in,out resIter The residual vector containing the CL and CD residuals at 4th and 5th index position
References abortVariable, calcCoef(), wing_t::cd, wing_t::cl, doCalcWing, elem_t::dt, E, evalRecordPoints(), firstElem, isStationary, recordPoint_t::nPoints, recordPoint, resFile, RHO, VX, VY, and wing.
Referenced by timeDisc().
calcErrors()
void calcErrors (double time)
Calculate L1, L2, and Linf error norms, between the flow solution and the exact solution.
Parameters
 in time Calculation time at output
References elem_t::bary, elem, exactFunc(), intExactFunc, NDIM, nElems, elem_t::nGP, NVAR, P, elem_t::pVar, RHO, spatialReconstruction(), totalArea_q, elem_t::u_x, elem_t::u_y, VX, VY, elem_t::wGP, X, elem_t::xGP, and Y.
Referenced by timeDisc().
globalResidual()
void globalResidual (double resIter[NVAR+2])
Calculate the global residual of the conservative variables.
Parameters
 in,out resIter The residual vector containing the residuals of the conservative variables at the first four positions
References elem_t::area, E, elem, MX, MY, nElems, NVAR, RHO, totalArea_q, and elem_t::u_t.
Referenced by explicitTimeStepEuler(), explicitTimeStepRK(), and implicitTimeStep().
Variable Documentation
doCalcWing
bool doCalcWing
calculate CL CD flag
Referenced by analyze(), freeAnalyze(), initAnalyze(), and timeDisc().
hasExactSolution
bool hasExactSolution
exact solution existence flag
Referenced by dataOutput(), initAnalyze(), and timeDisc().
recordPoint
recordPoint_t recordPoint
record flow field at a specific point
Referenced by analyze(), evalRecordPoints(), initAnalyze(), initRecordPoints(), and timeDisc().
wing
wing_t wing
holds data for coefficient calculation
Referenced by analyze(), calcCoef(), freeAnalyze(), initWing(), readWing(), and timeDisc().