ccfd/src/analyze.c File Reference
Contains functions for analyzing flow results.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include `analyze.h`
#include `readInTools.h`
#include `timeDiscretization.h`
#include `output.h`
#include `memTools.h`
#include `reconstruction.h`
#include `exactFunction.h`
#include `equation.h`
#include `initialCondition.h`
Functions
void initRecordPoints (void)
Initialize recording points.
void initWing (void)
Initialize required data for calculation of CL and CD.
void readWing (void)
Get parameters for calculating aerodynamic coefficients.
void initAnalyze (void)
Initialize the analysis function.
void calcCoef (void)
Calculate CL and CD around the specified wall.
void evalRecordPoints (double time)
Evaluation of recording points.
void analyze (double time, long iter, double resIter[NVAR+2])
Compute aerodynamic coefficients and extract values at record points.
void calcErrors (double time)
Calculate L1, L2, and Linf error norms, between the flow solution and the exact solution.
void globalResidual (double resIter[NVAR+2])
Calculate the global residual of the conservative variables.
void freeAnalyze (void)
Free all memory that was allocated for the wing evaluation.
Variables
bool doCalcWing
wing_t wing
recordPoint_t recordPoint
bool hasExactSolution
Detailed Description
Contains functions for analyzing flow results.
Author
hhh
Date
Sun 29 Mar 2020 06:29:36 PM CEST
Function Documentation
analyze()
void analyze (double time, long iter, double resIter[NVAR+2])
Compute aerodynamic coefficients and extract values at record points.
Parameters
 in time Calculation time at output
 in iter Iteration count at output
 in,out resIter The residual vector containing the CL and CD residuals at 4th and 5th index position
References abortVariable, calcCoef(), wing_t::cd, wing_t::cl, doCalcWing, elem_t::dt, E, evalRecordPoints(), firstElem, isStationary, recordPoint_t::nPoints, recordPoint, resFile, RHO, VX, VY, and wing.
Referenced by timeDisc().
calcErrors()
void calcErrors (double time)
Calculate L1, L2, and Linf error norms, between the flow solution and the exact solution.
Parameters
 in time Calculation time at output
References elem_t::bary, elem, exactFunc(), intExactFunc, NDIM, nElems, elem_t::nGP, NVAR, P, elem_t::pVar, RHO, spatialReconstruction(), totalArea_q, elem_t::u_x, elem_t::u_y, VX, VY, elem_t::wGP, X, elem_t::xGP, and Y.
Referenced by timeDisc().
evalRecordPoints()
void evalRecordPoints (double time)
Evaluation of recording points.
Parameters
 in time Calculation time at output
References elem_t::dt, recordPoint_t::elem, recordPoint_t::ioFile, recordPoint_t::nPoints, P, elem_t::pVar, recordPoint, RHO, VX, and VY.
Referenced by analyze().
globalResidual()
void globalResidual (double resIter[NVAR+2])
Calculate the global residual of the conservative variables.
Parameters
 in,out resIter The residual vector containing the residuals of the conservative variables at the first four positions
References elem_t::area, E, elem, MX, MY, nElems, NVAR, RHO, totalArea_q, and elem_t::u_t.
Referenced by explicitTimeStepEuler(), explicitTimeStepRK(), and implicitTimeStep().
Variable Documentation
doCalcWing
bool doCalcWing
calculate CL CD flag
Referenced by analyze(), freeAnalyze(), initAnalyze(), and timeDisc().
hasExactSolution
bool hasExactSolution
exact solution existence flag
Referenced by dataOutput(), initAnalyze(), and timeDisc().
recordPoint
recordPoint_t recordPoint
record flow field at a specific point
Referenced by analyze(), evalRecordPoints(), initAnalyze(), initRecordPoints(), and timeDisc().
wing
wing_t wing
holds data for coefficient calculation
Referenced by analyze(), calcCoef(), freeAnalyze(), initWing(), readWing(), and timeDisc().