ccfd/src/boundary.c File Reference
Contains the functions for initializing and applying boundary conditions.
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include `main.h`
#include `boundary.h`
#include `readInTools.h`
#include `equation.h`
#include `mesh.h`
#include `equationOfState.h`
#include `exactFunction.h`
Functions
void initBoundary (void)
Initialize boundary conditions.
void boundary (side_t *aSide, double time, double int_pVar[NVAR], double ghost_pVar[NVAR], double x[NDIM])
Set boundary condition value at x.
void setBCatSides (double time)
Set the ghost values at sides.
void setBCatBarys (double time)
Set the ghost values at elements.
void freeBoundary (void)
Free all memory that was allocated for the boundary conditions.
Variables
boundary_t * firstBC
int nBC
bool isPeriodic
Detailed Description
Contains the functions for initializing and applying boundary conditions.
Author
hhh
Date
Tue 24 Mar 2020 10:10:51 AM CET
Function Documentation
boundary()
void boundary (side_t * aSide, double time, double int_pVar[NVAR], double ghost_pVar[NVAR], double x[NDIM])
Set boundary condition value at x.
Parameters
 in aSide Pinter to a boundary side
 in time Computation time at calculation
 in int_pVar Internal cell primitive variables state
 out ghost_pVar Ghost cell primitive variables state
 in x Barycenter coordinates of the ghost cell
References side_t::BC, boundary_t::BCtype, CHARACTERISTIC, charCons(), side_t::connection, consChar(), consPrim(), boundary_t::exactFunc, exactFunc(), EXACTSOL, gam, INFLOW, mu, MY, side_t::n, NDIM, NVAR, OUTFLOW, P, PRESSURE_OUT, primCons(), boundary_t::pVar, RHO, SLIPWALL, VX, VY, WALL, X, and Y.
Referenced by setBCatBarys(), and setBCatSides().
setBCatBarys()
void setBCatBarys (double time)
Set the ghost values at elements.
Parameters
 in time Computation time at calculation
References elem_t::bary, BCside, boundary(), side_t::connection, side_t::elem, nBCsides, and elem_t::pVar.
Referenced by spatialReconstruction().
setBCatSides()
void setBCatSides (double time)
Set the ghost values at sides.
Parameters
 in time Computation time at calculation
References elem_t::bary, BCside, boundary(), side_t::connection, side_t::elem, side_t::GP, nBCsides, NDIM, side_t::pVar, X, and Y.
Referenced by fvTimeDerivative().
Variable Documentation
firstBC
boundary_t* firstBC
pointer to the first boundary condition
Referenced by cgnsWriteMesh(), createMesh(), freeBoundary(), initBoundary(), and initWing().
isPeriodic
bool isPeriodic
periodic boundary condition flag
Referenced by cgnsWriteMesh(), and connectPeriodicBC().
nBC
int nBC
number of boundary conditions
Referenced by cgnsWriteMesh(), and initBoundary().