ccfd/src/equationOfState.h File Reference
#include `main.h`
Functions
void primCons (const double pVar[NVAR], double cVar[NVAR])
Convert primitive variables into conservative variables.
void consPrim (const double cVar[NVAR], double pVar[NVAR])
Convert conservative variables into primitive variables.
void consChar (double cVar[NVAR], double charac[3], double pVarRef[NVAR])
Convert conservative variables to characteristic variables.
void charCons (double charac[3], double cVar[NVAR], double pVarRef[NVAR])
Convert characteristic variables to conservative variables.
Detailed Description
Author
hhh
Date
Sat 28 Mar 2020 09:45:50 PM CET
Function Documentation
charCons()
void charCons (double charac[3], double cVar[NVAR], double pVarRef[NVAR])
Convert characteristic variables to conservative variables.
Parameters
 in charac Characteristic variable vector
 out cVar Conservative variable vector
 in pVarRef Reference primitive variable vector
References E, gam, gam1q, MX, P, RHO, and VX.
Referenced by boundary().
consChar()
void consChar (double cVar[NVAR], double charac[3], double pVarRef[NVAR])
Convert conservative variables to characteristic variables.
Parameters
 in cVar Conservative variable vector
 out charac Characteristic variable vector
 in pVarRef Reference primitive variable vector
References E, gam, gam1q, P, RHO, and VX.
Referenced by boundary().
consPrim()
void consPrim (const double cVar[NVAR], double pVar[NVAR])
Convert conservative variables into primitive variables.
This function is used during reconstruction, therefore it has to be checked if the resulting primitive variables are negative. It that is the case, they are set to zero.
Parameters
 in cVar Conservative variable vector
 out pVar Primitive variable vector
References E, gam1, MX, MY, P, RHO, VX, and VY.
Referenced by boundary(), exactFunc(), explicitTimeStepEuler(), explicitTimeStepRK(), implicitTimeStep(), and matrixVector().
primCons()
void primCons (const double pVar[NVAR], double cVar[NVAR])
Convert primitive variables into conservative variables.
Parameters
 in pVar Primitive variable vector
 out cVar Conservative variable vector
References E, gam1q, MX, MY, P, RHO, VX, and VY.
Referenced by boundary(), and setInitialCondition().