ccfd/src/exactRiemann.c File Reference
Contains the function to calculate the exact Riemann flux.
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include `equation.h`
Functions
void preFun (double *f, double *fd, double p, double rhok, double pk, double ck)
Helper function for exactRiemann
void exactRiemann (double rhol, double rhor, double *rho, double ul, double ur, double *u, double pl, double pr, double *p, double al, double ar, double s)
Calculate the exact solution to the Riemann problem.
Variables
double G [9]
double tol = 1e-6
int nIter = 1000
Detailed Description
Contains the function to calculate the exact Riemann flux.
Author
hhh
Date
Sun 29 Mar 2020 12:35:17 PM CEST
Function Documentation
exactRiemann()
void exactRiemann (double rhol, double rhor, double * rho, double ul, double ur, double * u, double pl, double pr, double * p, double al, double ar, double s)
Calculate the exact solution to the Riemann problem.
Parameters
 in rhol Left side density
 in rhor Right side density
 out rho The resulting density
 in ul Left side velocity
 in ur Right side velocity
 out u Resulting velocity
 in pl Left side pressure
 in pr Right side pressure
 out p Resulting pressure
 in al Left side speed of sound
 in ar Right side speed of sound
 in s Speed of the discontinuity
References G, gam, nIter, preFun(), and tol.
Referenced by exactFunc(), and flux_god().
preFun()
void preFun (double * f, double * fd, double p, double rhok, double pk, double ck)
Helper function for exactRiemann
Parameters
 out f Flux
 out fd Flux difference
 in p Pressure
 in rhok Critical density
 in pk Critical pressure
 in ck Critical speed of sound
References G.
Referenced by exactRiemann().
Variable Documentation
G
double G[9]
gamma vector
Referenced by exactRiemann(), and preFun().
nIter
int nIter = 1000
maximum number of iterations
Referenced by exactRiemann().
tol
double tol = 1e-6
tolerance for the iteration
Referenced by exactRiemann().