ccfd/src/exactRiemann.h File Reference
Functions
void exactRiemann (double rhol, double rhor, double *rho, double ul, double ur, double *u, double pl, double pr, double *p, double al, double ar, double s)
Calculate the exact solution to the Riemann problem.
Detailed Description
Date
Sun 29 Mar 2020 12:35:26 PM CEST
Author
hhh
Function Documentation
exactRiemann()
void exactRiemann (double rhol, double rhor, double * rho, double ul, double ur, double * u, double pl, double pr, double * p, double al, double ar, double s)
Calculate the exact solution to the Riemann problem.
Parameters
 in rhol Left side density
 in rhor Right side density
 out rho The resulting density
 in ul Left side velocity
 in ur Right side velocity
 out u Resulting velocity
 in pl Left side pressure
 in pr Right side pressure
 out p Resulting pressure
 in al Left side speed of sound
 in ar Right side speed of sound
 in s Speed of the discontinuity
References G, gam, nIter, preFun(), and tol.
Referenced by exactFunc(), and flux_god().