ccfd/src/exactFunction.h File Reference
Functions
void exactFunc (int iExactFunc, double x[NDIM], double time, double pVar[NVAR])
Calculate an exact function.
Detailed Description
Author
hhh
Date
Sat 28 Mar 2020 05:55:25 PM CET
Function Documentation
exactFunc()
void exactFunc (int iExactFunc, double x[NDIM], double time, double pVar[NVAR])
Calculate an exact function.
This function contains the following exact functions:
1: Richtmyer-Meshkov
2: Gaussian pressure pulse
3: Sinewave
4: Double mach reflection
5: 1D Riemann problem
6: 1D sine wave
Parameters
 in iExactFunc The exact function control
 in x The coordinates for which to calculate the exact function
 in time The time for which to compute the exact value
 out pVar The resulting vector of primitive variables
References consPrim(), dxRef, E, exactRiemann(), gam, gam1, NVAR, P, pi, R, refState, RHO, rp1Dinterface, sqrt3q, VX, VY, X, xMax, xMin, Y, yMax, and yMin.
Referenced by boundary(), calcErrors(), cgnsOutput(), csvOutput(), curveOutput(), and setInitialCondition().