ccfd/src/finiteVolume.h File Reference
Functions
void initFV (void)
Initialize the finite volume method.
void fvTimeDerivative (double time)
Perform the spacial operator of the finite volume scheme.
Variables
int spatialOrder
int fluxFunction
Detailed Description
Author
hhh
Date
Fri 27 Mar 2020 05:09:57 PM CET
Function Documentation
fvTimeDerivative()
void fvTimeDerivative (double time)
Perform the spacial operator of the finite volume scheme.
First, the local time step is calculated, then spacial gradients inside of the cells are reconstructed. Following that, the boundary conditions at the sides are applied and the numerical flux is calculated, using the specified flux function. Finally, the source term is evaluated and the time derivatives of all the elements are calculated.
Parameters
 in time Calculation time at which to perform the finite volume differentiation
References elem_t::areaq, calcSource(), doCalcSource, elem_t::dt, elem_t::dtLoc, E, elem, elem_t::firstSide, side_t::flux, fluxCalculation(), nElems, side_t::nextElemSide, RHO, setBCatSides(), elem_t::source, spatialReconstruction(), timeOrder, elem_t::u_t, VX, and VY.
Referenced by buildMatrix(), explicitTimeStepEuler(), explicitTimeStepRK(), implicitTimeStep(), and matrixVector().
Variable Documentation
fluxFunction
int fluxFunction
the flux function to be used
spatialOrder
int spatialOrder
the spacial order to be used
Referenced by initFV(), and spatialReconstruction().