ccfd/src/fluxCalculation.c File Reference
Contains the flux calculation functions.
#include <math.h>
#include `main.h`
#include `mesh.h`
#include `equation.h`
#include `exactRiemann.h`
#include `boundary.h`
#include `linearSolver.h`
Functions
void flux_god (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
Godunov flux, which is the exact flux.
void flux_roe (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
Roe flux.
void flux_hll (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
HLL flux.
void flux_hlle (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
HLLE flux.
void flux_hllc (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
HLLC flux.
void flux_lxf (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
Lax-Friedrichs flux.
void flux_stw (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
Steger-Warming flux.
void flux_cen (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
Central flux.
void flux_ausmd (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
AUSMD flux.
void flux_ausmdv (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
AUSMDV flux.
void flux_vanleer (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
Van Leer flux.
void convectiveFlux (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
Select the convective flux.
void fluxCalculation (void)
Perform the flux calculation.
Detailed Description
Contains the flux calculation functions.
Author
hhh
Date
Tue 31 Mar 2020 05:18:40 PM CEST
Function Documentation
convectiveFlux()
void convectiveFlux (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
Select the convective flux.
Parameters
 in rhoL Left side density
 in rhoR Right side density
 in vxL Left side x-velocity
 in vxR Right side x-velocity
 in vyL Left side y-velocity
 in vyR Right side y-velocity
 in pL Left side pressure
 in pR Right side pressure
 out fluxLoc The local numeric flux
References AUSMD, AUSMDV, CEN, flux_ausmd(), flux_ausmdv(), flux_cen(), flux_god(), flux_hll(), flux_hllc(), flux_hlle(), flux_lxf(), flux_roe(), flux_stw(), flux_vanleer(), GOD, HLL, HLLC, HLLE, iFlux, LXF, ROE, STW, and VANLEER.
Referenced by fluxCalculation().
flux_ausmd()
void flux_ausmd (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
AUSMD flux.
Parameters
 in rhoL Left side density
 in rhoR Right side density
 in vxL Left side x-velocity
 in vxR Right side x-velocity
 in vyL Left side y-velocity
 in vyR Right side y-velocity
 in pL Left side pressure
 in pR Right side pressure
 out fluxLoc The local numeric flux
References gam, and gam1q.
Referenced by convectiveFlux().
flux_ausmdv()
void flux_ausmdv (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
AUSMDV flux.
Bug
Bug This function produces incorrect output, refrain from using it for the time being
Parameters
 in rhoL Left side density
 in rhoR Right side density
 in vxL Left side x-velocity
 in vxR Right side x-velocity
 in vyL Left side y-velocity
 in vyR Right side y-velocity
 in pL Left side pressure
 in pR Right side pressure
 out fluxLoc The local numeric flux
References gam, and gam1q.
Referenced by convectiveFlux().
flux_cen()
void flux_cen (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
Central flux.
Note
This flux is unconditionally unstable, it can be stabilized by adding artificial viscosity (Jameson method). This is not implemented, however.
Parameters
 in rhoL Left side density
 in rhoR Right side density
 in vxL Left side x-velocity
 in vxR Right side x-velocity
 in vyL Left side y-velocity
 in vyR Right side y-velocity
 in pL Left side pressure
 in pR Right side pressure
 out fluxLoc The local numeric flux
References gam1q.
Referenced by convectiveFlux().
flux_god()
void flux_god (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
Godunov flux, which is the exact flux.
Parameters
 in rhoL Left side density
 in rhoR Right side density
 in vxL Left side x-velocity
 in vxR Right side x-velocity
 in vyL Left side y-velocity
 in vyR Right side y-velocity
 in pL Left side pressure
 in pR Right side pressure
 out fluxLoc The local numeric flux
References exactRiemann(), gam, and gam1.
Referenced by convectiveFlux().
flux_hll()
void flux_hll (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
HLL flux.
Parameters
 in rhoL Left side density
 in rhoR Right side density
 in vxL Left side x-velocity
 in vxR Right side x-velocity
 in vyL Left side y-velocity
 in vyR Right side y-velocity
 in pL Left side pressure
 in pR Right side pressure
 out fluxLoc The local numeric flux
References gam, gam1, gam1q, MX, and NVAR.
Referenced by convectiveFlux().
flux_hllc()
void flux_hllc (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
HLLC flux.
Parameters
 in rhoL Left side density
 in rhoR Right side density
 in vxL Left side x-velocity
 in vxR Right side x-velocity
 in vyL Left side y-velocity
 in vyR Right side y-velocity
 in pL Left side pressure
 in pR Right side pressure
 out fluxLoc The local numeric flux
References gam, gam1, gam1q, MX, and NVAR.
Referenced by convectiveFlux().
flux_hlle()
void flux_hlle (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
HLLE flux.
Parameters
 in rhoL Left side density
 in rhoR Right side density
 in vxL Left side x-velocity
 in vxR Right side x-velocity
 in vyL Left side y-velocity
 in vyR Right side y-velocity
 in pL Left side pressure
 in pR Right side pressure
 out fluxLoc The local numeric flux
References gam, gam1q, MX, and NVAR.
Referenced by convectiveFlux().
flux_lxf()
void flux_lxf (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
Lax-Friedrichs flux.
Parameters
 in rhoL Left side density
 in rhoR Right side density
 in vxL Left side x-velocity
 in vxR Right side x-velocity
 in vyL Left side y-velocity
 in vyR Right side y-velocity
 in pL Left side pressure
 in pR Right side pressure
 out fluxLoc The local numeric flux
References gam, gam1q, and NVAR.
Referenced by convectiveFlux().
flux_roe()
void flux_roe (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
Roe flux.
Parameters
 in rhoL Left side density
 in rhoR Right side density
 in vxL Left side x-velocity
 in vxR Right side x-velocity
 in vyL Left side y-velocity
 in vyR Right side y-velocity
 in pL Left side pressure
 in pR Right side pressure
 out fluxLoc The local numeric flux
References gam, gam1, gam1q, and gam2.
Referenced by convectiveFlux().
flux_stw()
void flux_stw (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
Steger-Warming flux.
Parameters
 in rhoL Left side density
 in rhoR Right side density
 in vxL Left side x-velocity
 in vxR Right side x-velocity
 in vyL Left side y-velocity
 in vyR Right side y-velocity
 in pL Left side pressure
 in pR Right side pressure
 out fluxLoc The local numeric flux
References gam, gam1, and gam1q.
Referenced by convectiveFlux().
flux_vanleer()
void flux_vanleer (double rhoL, double rhoR, double vxL, double vxR, double vyL, double vyR, double pL, double pR, double fluxLoc[4])
Van Leer flux.
Parameters
 in rhoL Left side density
 in rhoR Right side density
 in vxL Left side x-velocity
 in vxR Right side x-velocity
 in vyL Left side y-velocity
 in vyR Right side y-velocity
 in pL Left side pressure
 in pR Right side pressure
 out fluxLoc The local numeric flux
References gam, gam1, and gam1q.
Referenced by convectiveFlux().
fluxCalculation()
void fluxCalculation (void)
Perform the flux calculation.
Calculation of left and right state, the velocity vector is transformed into the normal system of the cell interfaces. The function finishes with a back rotation of the velocity vector into global coordinate system.
References side_t::baryBaryDist, side_t::baryBaryVec, side_t::connection, convectiveFlux(), E, side_t::elem, side_t::flux, side_t::len, MX, MY, side_t::n, NDIM, nSides, NVAR, P, side_t::pVar, elem_t::pVar, RHO, side, elem_t::u_x, elem_t::u_y, VX, VY, X, and Y.
Referenced by fvTimeDerivative().