ccfd/src/memTools.h File Reference
#include `cgnslib.h`
Functions
long ** dyn2DintArray (long I, long J)
Allocate a dynamic 2D array of integers.
cgsize_t ** dyn2DcgsizeArray (long I, long J)
Allocate a dynamic 2D array of cgsize_t.
double ** dyn2DdblArray (long I, long J)
Allocate a dynamic 2D array of doubles.
long *** dyn3DintArray (long I, long J, long K)
Allocate a dynamic 3D array of integers.
double *** dyn3DdblArray (long I, long J, long K)
Allocate a dynamic 3D array of doubles.
double **** dyn4DdblArray (long I, long J, long K, long L)
Allocate a dynamic 4D array of doubles.
char ** dynStringArray (long I, long J)
Allocate a dynamic array of strings.
Detailed Description
Author
hhh
Date
Fri 27 Mar 2020 02:38:45 PM CET
Function Documentation
dyn2DcgsizeArray()
cgsize_t** dyn2DcgsizeArray (long I, long J)
Allocate a dynamic 2D array of cgsize_t.
Parameters
 in I Number of elements in the first dimension
 in J Number of elements in the second dimension
Returns
Pointer to a 2D cgsize_t array
Referenced by cgnsWriteMesh().
dyn2DdblArray()
double** dyn2DdblArray (long I, long J)
Allocate a dynamic 2D array of doubles.
Parameters
 in I Number of elements in the first dimension
 in J Number of elements in the second dimension
Returns
Pointer to a 2D double array
Referenced by cgnsWriteMesh(), createCartMesh(), createReconstructionInfo(), csvOutput(), curveOutput(), initInitialCondition(), initLinearSolver(), initRecordPoints(), initTimeDisc(), readCGNS(), readEMC2(), and readGmsh().
dyn2DintArray()
long** dyn2DintArray (long I, long J)
Allocate a dynamic 2D array of integers.
Parameters
 in I Number of elements in the first dimension
 in J Number of elements in the second dimension
Returns
Pointer to a 2D integer array
Referenced by createCartMesh(), readCGNS(), readEMC2(), and readGmsh().
dyn3DdblArray()
double*** dyn3DdblArray (long I, long J, long K)
Allocate a dynamic 3D array of doubles.
Parameters
 in I Number of elements in the first dimension
 in J Number of elements in the second dimension
 in K Number of elements in the third dimension
Returns
Pointer to a 3D double array
Referenced by initLinearSolver().
dyn3DintArray()
long*** dyn3DintArray (long I, long J, long K)
Allocate a dynamic 3D array of integers.
Parameters
 in I Number of elements in the first dimension
 in J Number of elements in the second dimension
 in K Number of elements in the third dimension
Returns
Pointer to a 3D integer array
dyn4DdblArray()
double**** dyn4DdblArray (long I, long J, long K, long L)
Allocate a dynamic 4D array of doubles.
Parameters
 in I Number of elements in the first dimension
 in J Number of elements in the second dimension
 in K Number of elements in the third dimension
 in L Number of elements in the fourth dimension
Returns
Pointer to a 4D double array
dynStringArray()
char** dynStringArray (long I, long J)
Allocate a dynamic array of strings.
Parameters
 in I Number of elements in the first dimension
 in J String length of each element
Returns
Pointer to a string array