ccfd/src/output.c File Reference
Contains all functions used for writing flow solutions.
#include <stdio.h>
#include <string.h>
#include <omp.h>
#include <math.h>
#include `main.h`
#include `output.h`
#include `readInTools.h`
#include `timeDiscretization.h`
#include `analyze.h`
#include `equation.h`
#include `exactFunction.h`
#include `cgnslib.h`
#include `memTools.h`
Functions
void initOutput (void)
Initialize output.
void csvOutput (char fileName[STRLEN], double time, bool doExact)
Tabular CSV output, only for 1D data.
void cgnsOutput (char fileName[STRLEN], double time, bool doExact)
Write solution to CGNS file.
void curveOutput (char fileName[STRLEN], double time, bool doExact)
Curve data output, only for 1D data.
void dataOutput (double time, long iter)
Perform a data output, dependent on the output format.
void cgnsFinalizeOutput (void)
Finalize CGNS output.
void finalizeDataOutput (void)
Finalize the data output, if necessary.
void cgnsWriteMesh (void)
Write the generated mesh to a CGNS mesh file.
void freeOutputTimes (void)
Free all memory that was allocated for the output times.
Variables
char strOutFile [STRLEN]
double IOtimeInterval
int IOiterInterval
int iVisuProg
char parameterFile [STRLEN]
FILE * resFile
bool doErrorOutput
outputTime_t * outputTimes
Detailed Description
Contains all functions used for writing flow solutions.
Author
hhh
Date
Mon 23 Mar 2020 10:42:06 PM CET
Function Documentation
cgnsFinalizeOutput()
void cgnsFinalizeOutput (void)
Finalize CGNS output.
This function creates a <case>_Master.cgns file that has links to all the output times of previous flow solutions. This makes it easier to load an entire case into ParaView.
References gridFile, isStationary, outputTime_t::iter, nElems, outputTime_t::next, nNodes, nQuads, nTrias, outputTimes, STRLEN, strOutFile, and outputTime_t::time.
Referenced by finalizeDataOutput().
cgnsOutput()
void cgnsOutput (char fileName[STRLEN], double time, bool doExact)
Write solution to CGNS file.
Parameters
 in fileName The name of the output file
 in time The computational time of the output result
 in doExact If the exact exact solution should be written, instead of the computed flow results
References elem_t::bary, exactFunc(), firstElem, gridFile, elem_t::id, intExactFunc, nElems, elem_t::next, nNodes, nQuads, nTrias, NVAR, P, elem_t::pVar, RHO, STRLEN, timeOverall, VX, and VY.
Referenced by dataOutput().
csvOutput()
void csvOutput (char fileName[STRLEN], double time, bool doExact)
Tabular CSV output, only for 1D data.
Parameters
 in fileName The name of the output file
 in time The computational time of the output result
 in doExact If the exact exact solution should be written, instead of the computed flow results
References elem_t::bary, dyn2DdblArray(), exactFunc(), firstElem, intExactFunc, nElems, elem_t::next, NVAR, P, elem_t::pVar, RHO, VX, and X.
Referenced by dataOutput().
curveOutput()
void curveOutput (char fileName[STRLEN], double time, bool doExact)
Curve data output, only for 1D data.
Parameters
 in fileName The name of the output file
 in time The computational time of the output result
 in doExact If the exact exact solution should be written, instead of the computed flow results
References elem_t::bary, dyn2DdblArray(), exactFunc(), firstElem, intExactFunc, nElems, elem_t::next, NVAR, P, elem_t::pVar, RHO, VX, and X.
Referenced by dataOutput().
dataOutput()
void dataOutput (double time, long iter)
Perform a data output, dependent on the output format.
Parameters
 in time The computational time of the output result
 in iter The iteration number of the output result
References CGNS, cgnsOutput(), CSV, csvOutput(), CURVE, curveOutput(), hasExactSolution, isStationary, outputTime_t::iter, iVisuProg, outputTime_t::next, outputTimes, STRLEN, strOutFile, and outputTime_t::time.
Referenced by timeDisc().
Variable Documentation
doErrorOutput
bool doErrorOutput
error output flag
IOiterInterval
int IOiterInterval
iteration interval for data output
Referenced by initOutput(), initTimeDisc(), and timeDisc().
IOtimeInterval
double IOtimeInterval
time interval for data output
Referenced by initOutput(), initTimeDisc(), and timeDisc().
iVisuProg
int iVisuProg
output format code
Referenced by dataOutput(), finalizeDataOutput(), initMesh(), and initOutput().
outputTimes
outputTime_t* outputTimes
the first output time object
Referenced by cgnsFinalizeOutput(), dataOutput(), freeOutputTimes(), and main().
parameterFile
char parameterFile[STRLEN]
name of the parameter file
resFile
FILE* resFile
residual file pointer
Referenced by analyze(), initAnalyze(), and timeDisc().
strOutFile
char strOutFile[STRLEN]
name of the output file
Referenced by calcCoef(), cgnsFinalizeOutput(), dataOutput(), initAnalyze(), initMesh(), initOutput(), and initRecordPoints().