ccfd/src/readInTools.h File Reference
#include <stdbool.h>
#include `main.h`
Functions
void fillCmds (char iniFileName[STRLEN])
Read parameter file and create commands list.
char * getStr (const char *key, const char *proposal)
Get a string from the commands list.
int countKeys (const char *key, const int proposal)
Count how often a key appears.
int getInt (const char *key, const char *proposal)
Get an integer from the commands list.
double getDbl (const char *key, const char *proposal)
Get a double from the commands list.
bool getBool (const char *key, const char *proposal)
Get a boolean from the commands list.
int * getIntArray (const char *key, const int N, const char *proposal)
Get an integer array from the commands list.
double * getDblArray (const char *key, const int N, const char *proposal)
Get a double array from the commands list.
void ignoredCmds (void)
Print out all remaining commands in the list.
Detailed Description
Author
hhh
Date
Sat 21 Mar 2020 10:51:13 AM CET
Function Documentation
countKeys()
int countKeys (const char * key, const int proposal)
Count how often a key appears.
Count all occurrences of key in parameter file and return them. If the key is not specified, the proposal will be returned. If the proposal is -1, but the key is not in the list, an error will be thrown.
Parameters
 in key Key string of the command to be found
 in proposal The default value that is used if the key was not
Returns
How often the key appeared in the command list
References firstCmd, and cmd_t::next.
Referenced by initBoundary().
fillCmds()
void fillCmds (char iniFileName[STRLEN])
Read parameter file and create commands list.
Read .ini file and parse each line into a cmd_t object. All cmd_t objects are connected in a list of commands starting with firstCmd.
Parameters
 in iniFileName The name of the parameter file
References firstCmd, cmd_t::key, cmd_t::next, cmd_t::prev, STRLEN, and cmd_t::value.
Referenced by main().
getBool()
bool getBool (const char * key, const char * proposal)
Get a boolean from the commands list.
Find the key in the command list and return the corresponding value. If the key is not specified, the proposal will be returned. If the proposal is NULL, but the key is not in the list, an error will be thrown. The value in the parameter file is accepted as true, if it is a 'T', 't', 'True', or 'true', otherwise it is false.
Parameters
 in key Key string of the command to be found
 in proposal The default value that is used if the key was not
Returns
The value of the parameter, or the default value
References findCmd().
Referenced by initAnalyze(), initBoundary(), initEquation(), initLinearSolver(), initTimeDisc(), and main().
getDbl()
double getDbl (const char * key, const char * proposal)
Get a double from the commands list.
Find the key in the command list and return the corresponding value. If the key is not specified, the proposal will be returned. If the proposal is NULL, but the key is not in the list, an error will be thrown.
Parameters
 in key Key string of the command to be found
 in proposal The default value that is used if the key was not
Returns
The value of the parameter, or the default value
References findCmd().
Referenced by initBoundary(), initEquation(), initFV(), initInitialCondition(), initLinearSolver(), initOutput(), initTimeDisc(), and readWing().
getDblArray()
double* getDblArray (const char * key, const int N, const char * proposal)
Get a double array from the commands list.
Find the key in the command list and return the corresponding integer array. If the key is not specified, the proposal will be returned. If the proposal is NULL, but the key is not in the list, an error will be thrown.
Parameters
 in key Key string of the command to be found
 in N Length of the array that is to be read in
 in proposal The default value that is used if the key was not
Returns
A pointer to the value array of the parameter, or the default value array
References findCmd(), and STRLEN.
Referenced by initBoundary(), initInitialCondition(), initRecordPoints(), and readMesh().
getInt()
int getInt (const char * key, const char * proposal)
Get an integer from the commands list.
Find the key in the command list and return the corresponding value. If the key is not specified, the proposal will be returned. If the proposal is NULL, but the key is not in the list, an error will be thrown.
Parameters
 in key Key string of the command to be found
 in proposal The default value that is used if the key was not
Returns
The value of the parameter, or the default value
References findCmd().
Referenced by initAnalyze(), initBoundary(), initEquation(), initFV(), initInitialCondition(), initLinearSolver(), initOutput(), initTimeDisc(), readMesh(), and readWing().
getIntArray()
int* getIntArray (const char * key, const int N, const char * proposal)
Get an integer array from the commands list.
Find the key in the command list and return the corresponding integer array. If the key is not specified, the proposal will be returned. If the proposal is NULL, but the key is not in the list, an error will be thrown.
Parameters
 in key Key string of the command to be found
 in N Length of the array that is to be read in
 in proposal The default value that is used if the key was not
Returns
A pointer to the value array of the parameter, or the default value array
References findCmd(), and STRLEN.
Referenced by readMesh().
getStr()
char* getStr (const char * key, const char * proposal)
Get a string from the commands list.
Find the key in the command list and return the corresponding value. If the key is not specified, the proposal will be returned. If the proposal is NULL, but the key is not in the list, an error will be thrown.
Parameters
 in key Key string of the command to be found
 in proposal The default value that is used if the key was not
Returns
Pointer to the value string, containing the parameter, or the default value, if the parameter was not specified
References findCmd().
Referenced by initOutput(), and readMesh().