ccfd/src/readInTools.c File Reference
Provides functions for reading data from the .ini parameter file.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <stdbool.h>
#include `main.h`
Data Structures
struct cmd_t
A structure used to store the commands, read in from the parameter file.
Functions
void fillCmds (char iniFileName[STRLEN])
Read parameter file and create commands list.
void deleteCmd (cmd_t *aCmd)
Delete a single node of the command list.
char * findCmd (const char *key, char defMsg[8], const char *proposal)
Find a command in the commands list.
char * getStr (const char *key, const char *proposal)
Get a string from the commands list.
int countKeys (const char *key, const int proposal)
Count how often a key appears.
int getInt (const char *key, const char *proposal)
Get an integer from the commands list.
double getDbl (const char *key, const char *proposal)
Get a double from the commands list.
bool getBool (const char *key, const char *proposal)
Get a boolean from the commands list.
int * getIntArray (const char *key, const int N, const char *proposal)
Get an integer array from the commands list.
double * getDblArray (const char *key, const int N, const char *proposal)
Get a double array from the commands list.
void freeCmds (void)
Delete all commands in the commands list.
void ignoredCmds (void)
Print out all remaining commands in the list.
Variables
cmd_t * firstCmd
Detailed Description
Provides functions for reading data from the .ini parameter file.
Author
hhh
Date
Sat 21 Mar 2020 10:46:32 AM CET
Function Documentation
countKeys()
int countKeys (const char * key, const int proposal)
Count how often a key appears.
Count all occurrences of key in parameter file and return them. If the key is not specified, the proposal will be returned. If the proposal is -1, but the key is not in the list, an error will be thrown.
Parameters
 in key Key string of the command to be found
 in proposal The default value that is used if the key was not
Returns
How often the key appeared in the command list
References firstCmd, and cmd_t::next.
Referenced by initBoundary().
deleteCmd()
void deleteCmd (cmd_t * aCmd)
Delete a single node of the command list.
Before deleting the command, the previous command is connected to the next command and vice versa.
Parameters
 in aCmd A pointer to the command that is to be deleted
References firstCmd, cmd_t::next, and cmd_t::prev.
Referenced by findCmd().
fillCmds()
void fillCmds (char iniFileName[STRLEN])
Read parameter file and create commands list.
Read .ini file and parse each line into a cmd_t object. All cmd_t objects are connected in a list of commands starting with firstCmd.
Parameters
 in iniFileName The name of the parameter file
References firstCmd, cmd_t::key, cmd_t::next, cmd_t::prev, STRLEN, and cmd_t::value.
Referenced by main().
findCmd()
char* findCmd (const char * key, char defMsg[8], const char * proposal)
Find a command in the commands list.
Find the provided key in the list of commands, and return the address of the corresponding value string. Return NULL if key was not found. Once a key was read from the commands list, it is deleted from the list.
Parameters
 in key Key string of the command to be found
 out defMsg String, that indicates if an actual value or the proposal was returned
 in proposal The default value that is used if the key was not specified
Returns
Pointer to the value string, or NULL
References deleteCmd(), firstCmd, cmd_t::key, cmd_t::next, and cmd_t::value.
Referenced by getBool(), getDbl(), getDblArray(), getInt(), getIntArray(), and getStr().
getBool()
bool getBool (const char * key, const char * proposal)
Get a boolean from the commands list.
Find the key in the command list and return the corresponding value. If the key is not specified, the proposal will be returned. If the proposal is NULL, but the key is not in the list, an error will be thrown. The value in the parameter file is accepted as true, if it is a 'T', 't', 'True', or 'true', otherwise it is false.
Parameters
 in key Key string of the command to be found
 in proposal The default value that is used if the key was not
Returns
The value of the parameter, or the default value
References findCmd().
Referenced by initAnalyze(), initBoundary(), initEquation(), initLinearSolver(), initTimeDisc(), and main().
getDbl()
double getDbl (const char * key, const char * proposal)
Get a double from the commands list.
Find the key in the command list and return the corresponding value. If the key is not specified, the proposal will be returned. If the proposal is NULL, but the key is not in the list, an error will be thrown.
Parameters
 in key Key string of the command to be found
 in proposal The default value that is used if the key was not
Returns
The value of the parameter, or the default value
References findCmd().
Referenced by initBoundary(), initEquation(), initFV(), initInitialCondition(), initLinearSolver(), initOutput(), initTimeDisc(), and readWing().
getDblArray()
double* getDblArray (const char * key, const int N, const char * proposal)
Get a double array from the commands list.
Find the key in the command list and return the corresponding integer array. If the key is not specified, the proposal will be returned. If the proposal is NULL, but the key is not in the list, an error will be thrown.
Parameters
 in key Key string of the command to be found
 in N Length of the array that is to be read in
 in proposal The default value that is used if the key was not
Returns
A pointer to the value array of the parameter, or the default value array
References findCmd(), and STRLEN.
Referenced by initBoundary(), initInitialCondition(), initRecordPoints(), and readMesh().
getInt()
int getInt (const char * key, const char * proposal)
Get an integer from the commands list.
Find the key in the command list and return the corresponding value. If the key is not specified, the proposal will be returned. If the proposal is NULL, but the key is not in the list, an error will be thrown.
Parameters
 in key Key string of the command to be found
 in proposal The default value that is used if the key was not
Returns
The value of the parameter, or the default value
References findCmd().
Referenced by initAnalyze(), initBoundary(), initEquation(), initFV(), initInitialCondition(), initLinearSolver(), initOutput(), initTimeDisc(), readMesh(), and readWing().
getIntArray()
int* getIntArray (const char * key, const int N, const char * proposal)
Get an integer array from the commands list.
Find the key in the command list and return the corresponding integer array. If the key is not specified, the proposal will be returned. If the proposal is NULL, but the key is not in the list, an error will be thrown.
Parameters
 in key Key string of the command to be found
 in N Length of the array that is to be read in
 in proposal The default value that is used if the key was not
Returns
A pointer to the value array of the parameter, or the default value array
References findCmd(), and STRLEN.
Referenced by readMesh().
getStr()
char* getStr (const char * key, const char * proposal)
Get a string from the commands list.
Find the key in the command list and return the corresponding value. If the key is not specified, the proposal will be returned. If the proposal is NULL, but the key is not in the list, an error will be thrown.
Parameters
 in key Key string of the command to be found
 in proposal The default value that is used if the key was not
Returns
Pointer to the value string, containing the parameter, or the default value, if the parameter was not specified
References findCmd().
Referenced by initOutput(), and readMesh().
Variable Documentation
firstCmd
cmd_t* firstCmd
first command of the list
Referenced by countKeys(), deleteCmd(), fillCmds(), findCmd(), freeCmds(), and ignoredCmds().