ccfd/src/reconstruction.c File Reference
Contains the reconstruction and limiter functions.
#include <math.h>
#include `main.h`
#include `reconstruction.h`
#include `finiteVolume.h`
#include `mesh.h`
Functions
void limiterBarthJespersen (elem_t *aElem)
Limiter after Barth & Jespersen.
void limiterVenkatakrishnan (elem_t *aElem)
Limiter after Venkatakrishnan, with additional limiting parameter k.
void spatialReconstruction (double time)
Compute the gradients of dU/dx.
Variables
int limiter
double venk_k
Detailed Description
Contains the reconstruction and limiter functions.
Author
hhh
Date
Sat 28 Mar 2020 10:17:02 AM CET
Function Documentation
limiterBarthJespersen()
void limiterBarthJespersen (elem_t * aElem)
Limiter after Barth & Jespersen.
Note
2D, unstructured limiter
Parameters
 in aElem Pointer to an element
References side_t::connection, side_t::elem, elem_t::firstSide, side_t::GP, side_t::nextElemSide, NVAR, P, elem_t::pVar, RHO, elem_t::u_x, elem_t::u_y, VX, VY, X, and Y.
Referenced by spatialReconstruction().
limiterVenkatakrishnan()
void limiterVenkatakrishnan (elem_t * aElem)
Limiter after Venkatakrishnan, with additional limiting parameter k.
Note
2D, unstructured limiter
Parameters
 in aElem Pointer to an element
References side_t::connection, side_t::elem, elem_t::firstSide, side_t::GP, side_t::nextElemSide, NVAR, P, elem_t::pVar, RHO, elem_t::u_x, elem_t::u_y, elem_t::venkEps_sq, VX, VY, X, and Y.
Referenced by spatialReconstruction().
spatialReconstruction()
void spatialReconstruction (double time)
Compute the gradients of dU/dx.
Parameters
 in time Calculation time at which to perform the spatial reconstruction
References BARTHJESPERSEN, side_t::connection, side_t::elem, elem, elem_t::firstSide, side_t::GP, limiter, limiterBarthJespersen(), limiterVenkatakrishnan(), nElems, side_t::nextElemSide, NVAR, P, side_t::pVar, elem_t::pVar, RHO, setBCatBarys(), spatialOrder, elem_t::u_t, elem_t::u_x, elem_t::u_y, VENKATAKRISHNAN, VX, VY, side_t::w, X, and Y.
Referenced by calcErrors(), and fvTimeDerivative().
Variable Documentation
limiter
int limiter
limiter selection
Referenced by initFV(), and spatialReconstruction().
venk_k
double venk_k
constant for Venkatakrishnan limiter
Referenced by initFV().