ccfd/src/reconstruction.h File Reference
Functions
void spatialReconstruction (double time)
Compute the gradients of dU/dx.
Variables
int limiter
double venk_k
Detailed Description
Author
hhh
Date
Sat 28 Mar 2020 10:16:16 AM CET
Function Documentation
spatialReconstruction()
void spatialReconstruction (double time)
Compute the gradients of dU/dx.
Parameters
 in time Calculation time at which to perform the spatial reconstruction
References BARTHJESPERSEN, side_t::connection, elem, side_t::elem, elem_t::firstSide, side_t::GP, limiter, limiterBarthJespersen(), limiterVenkatakrishnan(), nElems, side_t::nextElemSide, NVAR, P, side_t::pVar, elem_t::pVar, RHO, setBCatBarys(), spatialOrder, elem_t::u_t, elem_t::u_x, elem_t::u_y, VENKATAKRISHNAN, VX, VY, side_t::w, X, and Y.
Referenced by calcErrors(), and fvTimeDerivative().
Variable Documentation
limiter
int limiter [extern]
limiter selection
Referenced by initFV(), and spatialReconstruction().
venk_k
double venk_k [extern]
constant for Venkatakrishnan limiter
Referenced by initFV().