ccfd/src/source.c File Reference
Contains the functions for initializing and evaluating the source term.
#include <math.h>
#include `main.h`
#include `equation.h`
#include `mesh.h`
Functions
void evalSource (int iSource, double x[NDIM], double time, double source[NVAR])
Evaluate the source term.
void calcSource (double time)
Calculate the contribution of the source terms.
Detailed Description
Contains the functions for initializing and evaluating the source term.
Author
hhh
Date
Wed 01 Apr 2020 12:25:11 PM CEST
Function Documentation
calcSource()
void calcSource (double time)
Calculate the contribution of the source terms.
Parameters
 in time The computation time at which the evaluate the source term
References E, elem, evalSource(), nElems, elem_t::nGP, NVAR, RHO, elem_t::source, sourceFunc, VX, VY, elem_t::wGP, and elem_t::xGP.
Referenced by fvTimeDerivative().
evalSource()
void evalSource (int iSource, double x[NDIM], double time, double source[NVAR])
Evaluate the source term.
Parameters
 in iSource The source control integer
 in x The coordinates at which to evaluate the source term
 in time The computation time at which the evaluate the source term
 out source The source term contribution
References E, gam, gam1, mu, pi, Pr, RHO, VX, VY, X, and Y.
Referenced by calcSource().