# CCFD Makefile (redirect)

.PHONY: clean allclean doc

all:
	@cd .. && $(MAKE) all --no-print-directory

libs:
	@cd .. && $(MAKE) libs --no-print-directory

clean:
	@cd .. && $(MAKE) clean --no-print-directory

allclean:
	@cd .. && $(MAKE) allclean --no-print-directory

doc:
	@cd .. && $(MAKE) doc --no-print-directory

run:
	@cd .. && $(MAKE) run --no-print-directory

debug:
	@cd .. && $(MAKE) debug --no-print-directory
