#
# CCFD Makefile (redirect)
#
# 'make' 	  : build libraries and executable
# 'make libs' 	  : build only libraries
# 'make clean' 	  : remove executable
# 'make allclean' : remove executable and libraries
# 'make doc'      : create the documentation with doxygen

.PHONY: clean allclean doc

default:
	@cd .. && $(MAKE) default --no-print-directory

all: default

libs:
	@cd .. && $(MAKE) libs --no-print-directory

clean:
	@cd .. && $(MAKE) clean --no-print-directory

allclean:
	@cd .. && $(MAKE) allclean --no-print-directory

doc:
	@cd .. && $(MAKE) doc --no-print-directory

run:
	@cd .. && $(MAKE) run --no-print-directory

debug:
	@cd .. && $(MAKE) debug --no-print-directory
