#
# CCFD Makefile (redirect)
#
# 'make' 	  : build libraries and executable
# 'make libs' 	  : build only libraries
# 'make clean' 	  : remove executable
# 'make allclean' : remove executable and libraries

.PHONY: default all clean allclean

default:
	@cd .. && $(MAKE) default --no-print-directory

all: default

libs:
	@cd .. && $(MAKE) libs --no-print-directory

clean:
	@cd .. && $(MAKE) clean --no-print-directory

allclean:
	@cd .. && $(MAKE) allclean --no-print-directory

run:
	@cd .. && $(MAKE) run --no-print-directory

debug:
	@cd .. && $(MAKE) debug --no-print-directory
